version: '3.9'

networks:
  foodorders-network:
    driver: bridge

services:
  foodorders-db:
    image: postgres:14
    environment:
      POSTGRES_DB: foodorders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - foodorders-network

  foodorders-api:
    image: foodorders-api
    command: ["/wait-for-it.sh", "foodorders-db:5432", "-t", "20", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: foodorders-db
    #ports:
    #  - "8080:8080"
    networks:
      - foodorders-network
    depends_on:
      - foodorders-db
    #deploy: // it's necessary remove ports property
      #replicas: 2

  foodorders-proxy:
    build: ./nginx
    image: foodorders-proxy
    ports:
      - "80:80"
    networks:
      - foodorders-network
    depends_on:
      - foodorders-api
