version: '3.1'

networks:
  foodorders-network:
    driver: bridge

services:
  foodorders-db:
    image: postgres:14
    environment:
      POSTGRES_DB: foodorders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - foodorders-network

  foodorders-api:
    image: foodorders-api
    environment:
      DB_HOST: foodorders-db
    ports:
      - "8080:8080"
    networks:
      - foodorders-network
    depends_on:
      - foodorders-db
