alter table if exists group_permission drop constraint if exists FK1xv049cqhqxtpiwxmsw0tae5i;
alter table if exists group_permission drop constraint if exists FKia4i2mnipadaulhbfoxyimh3b;
alter table if exists restaurant_payment_way drop constraint if exists FKe260pl4h9bldihnxvg11yshnl;
alter table if exists restaurant_payment_way drop constraint if exists FKay3103t7ctdn4s4hbf9noh5s2;
alter table if exists tab_cities drop constraint if exists FKly5fu1bua1x6dxp70ka976jbm;
alter table if exists tab_order_items drop constraint if exists FKoqwljok5p0j1dsd2m5gakvs2y;
alter table if exists tab_order_items drop constraint if exists FKptkbqw1ng1voes6j1vokjbj3b;
alter table if exists tab_orders drop constraint if exists FK54omags6hm7qj3s7dqrh0qh4w;
alter table if exists tab_orders drop constraint if exists FK7xtar1ov4awexhkyw67vmel3f;
alter table if exists tab_orders drop constraint if exists FKkya0nqop0lukmqqcg53bjyli5;
alter table if exists tab_orders drop constraint if exists FKx8blthipqk3gma8edfomx76x;
alter table if exists tab_products drop constraint if exists FKgs9b88pm5qvua6q0yd0vtxnfa;
alter table if exists tab_restaurants drop constraint if exists FKk15o36pk2am5ja9hkax80qwl4;
alter table if exists tab_restaurants drop constraint if exists FK8bmfs4fhfxffsks7ek277ypr5;
alter table if exists user_group drop constraint if exists FKlxbdphhhfkpr7lb24qv5cmyif;
alter table if exists user_group drop constraint if exists FKebhfvtltygo0xq3xbjigir3o6;
drop table if exists group_permission cascade;
drop table if exists restaurant_payment_way cascade;
drop table if exists tab_cities cascade;
drop table if exists tab_groups cascade;
drop table if exists tab_kitchens cascade;
drop table if exists tab_order_items cascade;
drop table if exists tab_orders cascade;
drop table if exists tab_payment_ways cascade;
drop table if exists tab_permissions cascade;
drop table if exists tab_products cascade;
drop table if exists tab_restaurants cascade;
drop table if exists tab_states cascade;
drop table if exists tab_users cascade;
drop table if exists user_group cascade;


create table group_permission (group_id int8 not null, permission_id int8 not null);
create table restaurant_payment_way (restaurant_id int8 not null, paymentway_id int8 not null);
create table tab_cities (id  bigserial not null, name varchar(255) not null, state_id int8 not null, primary key (id));
create table tab_groups (id  bigserial not null, created_at timestamp not null, name varchar(255) not null, updated_at timestamp not null, primary key (id));
create table tab_kitchens (id  bigserial not null, name varchar(255) not null, primary key (id));
create table tab_order_items (id  bigserial not null, amount int8 not null, created_at timestamp not null, observations varchar(255) not null, total_price numeric(19, 2) not null, unit_price numeric(19, 2) not null, updated_at timestamp not null, order_id int8 not null, product_id int8 not null, primary key (id));
create table tab_orders (id  bigserial not null, address_complement varchar(255), address_district varchar(255), address_number varchar(255), address_postalcode varchar(255), address_street varchar(255), confirmed_at timestamp, created_at timestamp not null, delivered_at timestamp, partial_price numeric(19, 2) not null, shipping_costs numeric(19, 2) not null, status varchar(255) not null, total_price numeric(19, 2) not null, updated_at timestamp not null, address_city_id int8, paymentway_id int8 not null, restaurant_id int8 not null, user_id int8 not null, primary key (id));
create table tab_payment_ways (id  bigserial not null, description varchar(255) not null, primary key (id));
create table tab_permissions (id  bigserial not null, description varchar(255) not null, name varchar(255) not null, primary key (id));
create table tab_products (id  bigserial not null, active boolean not null, created_at timestamp not null, description varchar(255) not null, name varchar(255) not null, price numeric(19, 2) not null, updated_at timestamp not null, restaurant_id int8 not null, primary key (id));
create table tab_restaurants (id  bigserial not null, address_complement varchar(255), address_district varchar(255), address_number varchar(255), address_postalcode varchar(255), address_street varchar(255), created_at timestamp not null, name varchar(255) not null, shipping_costs numeric(19, 2) not null, updated_at timestamp not null, address_city_id int8, kitchen_id int8 not null, primary key (id));
create table tab_states (id  bigserial not null, name varchar(255) not null, primary key (id));
create table tab_users (id  bigserial not null, created_at timestamp not null, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, updated_at timestamp not null, primary key (id));
create table user_group (user_id int8 not null, group_id int8 not null);
alter table if exists group_permission add constraint FK1xv049cqhqxtpiwxmsw0tae5i foreign key (permission_id) references tab_permissions;
alter table if exists group_permission add constraint FKia4i2mnipadaulhbfoxyimh3b foreign key (group_id) references tab_groups;
alter table if exists restaurant_payment_way add constraint FKe260pl4h9bldihnxvg11yshnl foreign key (paymentway_id) references tab_payment_ways;
alter table if exists restaurant_payment_way add constraint FKay3103t7ctdn4s4hbf9noh5s2 foreign key (restaurant_id) references tab_restaurants;
alter table if exists tab_cities add constraint FKly5fu1bua1x6dxp70ka976jbm foreign key (state_id) references tab_states;
alter table if exists tab_order_items add constraint FKoqwljok5p0j1dsd2m5gakvs2y foreign key (order_id) references tab_orders;
alter table if exists tab_order_items add constraint FKptkbqw1ng1voes6j1vokjbj3b foreign key (product_id) references tab_products;
alter table if exists tab_orders add constraint FK54omags6hm7qj3s7dqrh0qh4w foreign key (address_city_id) references tab_cities;
alter table if exists tab_orders add constraint FK7xtar1ov4awexhkyw67vmel3f foreign key (paymentway_id) references tab_payment_ways;
alter table if exists tab_orders add constraint FKkya0nqop0lukmqqcg53bjyli5 foreign key (restaurant_id) references tab_restaurants;
alter table if exists tab_orders add constraint FKx8blthipqk3gma8edfomx76x foreign key (user_id) references tab_users;
alter table if exists tab_products add constraint FKgs9b88pm5qvua6q0yd0vtxnfa foreign key (restaurant_id) references tab_restaurants;
alter table if exists tab_restaurants add constraint FKk15o36pk2am5ja9hkax80qwl4 foreign key (address_city_id) references tab_cities;
alter table if exists tab_restaurants add constraint FK8bmfs4fhfxffsks7ek277ypr5 foreign key (kitchen_id) references tab_kitchens;
alter table if exists user_group add constraint FKlxbdphhhfkpr7lb24qv5cmyif foreign key (group_id) references tab_groups;
alter table if exists user_group add constraint FKebhfvtltygo0xq3xbjigir3o6 foreign key (user_id) references tab_users;
